# Generated by Django 6.0.5 on 2026-06-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('session', models.CharField(max_length=64)),
                ('url', models.TextField(blank=True)),
                ('shasum', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='dashboard.ipgeolocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=64, unique=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('client_version', models.CharField(blank=True, max_length=255)),
                ('hassh', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dashboard.ipgeolocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('session', models.CharField(max_length=64)),
                ('command', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='dashboard.ipgeolocation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('session', 'timestamp', 'command'), name='unique_command_event')],
            },
        ),
    ]
