# Generated by Django 6.0.5 on 2026-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_filedownload_session_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownload',
            name='vt_detections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filedownload',
            name='vt_familia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filedownload',
            name='vt_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
